extends: stylelint-config-standard

ignoreFiles:
  - client/css/bootstrap.css

rules:
  indentation: tab
  # complains about FontAwesome
  font-family-no-missing-generic-family-keyword:
  # needs a lot of refactoring to be enabled
  no-descending-specificity:
