---
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Do not build on tags (GitHub only)
skip_tags: true

# Do not build feature branch with open pull requests
skip_branch_with_pr: true

environment:
  nodejs_version: '6'

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --frozen-lockfile
  - yarn build
  - yarn add mocha-appveyor-reporter
  - ps: (gc test/mocha.opts) -replace 'dot', 'mocha-appveyor-reporter' | sc test/mocha.opts
  - ps: (gc test/mocha-webpack.opts) -replace 'dot', 'mocha-appveyor-reporter' | sc test/mocha-webpack.opts

test_script:
  - node --version
  - yarn --version
  - yarn test

# cache npm modules
cache:
  - "%LOCALAPPDATA%\\Yarn"

# Don't actually build
build: off
